server:
  port: 8082

spring:
  application:
    name: connect-service
  config:
    import: optional:nacos:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
        enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: openiot123
      database: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Netty 配置
netty:
  port: 8888
  boss-threads: 1
  worker-threads: 4

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    com.openiot: debug
    io.netty: info
